### ISSUE TITLE
[not-a-bug] A follow-up to help/discussion on staredit samase thread

### ISSUE THREAD

**Issue by myocytebd** [neivv/mtl#1]
Follow-up to samase freeze/crash under wine: http://www.staredit.net/topic/17430/8/#174
I decided to put it github because staredit seems unable to format a readable rich text.

> Random crashing without crash handler running, and sometimes freezing definitely sounds like it's triggering one of the executable's protections that intentionally close the exe, often with int 29 so that the process exits without running any exception handlers.

> Running with `WINEDEBUG=+seh` may also help to get the information from a crash? Not sure if it works there.

This is the log file with `+seh` and non-empty directory, during which SC:R ends up freezed.
During the freezing period, lots of `trace:seh:dispatch_exception code=c0000005 flags=0 addr=00000000 ip=00000000` repeated.
(The last few prints was during or after linux side process termination and probably not relevant.)
Preceeding the bogus EXCEPTION_ACCESS_VIOLATIONs, there is a EXCEPTION_ILLEGAL_INSTRUCTION with a unique addr.
[wine.non_empty_freeze4.log](https://github.com/user-attachments/files/15964941/wine.non_empty_freeze4.log)
[samase.non_empty_freeze4.log](https://github.com/user-attachments/files/15964944/samase.non_empty_freeze4.log)

> But other than the log it'd be most helpful to know which instruction in the exe (address, relative to image base) it exactly is freezing / crashing, not sure if you can attach a debugger on freeze to get that information out with wine or anything. 

I can try to debug it, but I don't know which kind of site to catch.  
Looking at the wine log, the freezing period was after the actual fatal site and was probably too late.  

Above logs are generate by running `samase-0.8.31.exe` from the initial post.
> The zip also includes a 64-bit executable in case it changes anything and you have time to try it.

The 64-bit exe didn't freeze or crash over totally 40 min wall clock. So it appears fixed or greatly improved.  

> I have one guess of where the cause could be without any other information, if you could run this build of samase with --log and post the log file after startup it may be helpful (Does not have to hit the crash). 

This is a samase64 start-up log with non-empty directory, 5 min of game time (x10).  
[samase64.non_empty.log](https://github.com/user-attachments/files/15966470/samase64.non_empty.log)

This is a samase32 log with non-empty directory, which ended-up freezed.  
[samase32.non_empty_freeze0.log](https://github.com/user-attachments/files/15966865/samase32.non_empty_freeze0.log)
[wine.new0.non_empty_freeze0.partial.log](https://github.com/user-attachments/files/15966872/wine.new0.non_empty_freeze0.partial.log)
The wine log is imcomplete because I forgot to redirect it, but it looks quite similar to previous one. (last EXCEPTION_ILLEGAL_INSTRUCTION had same addr)

**Comment by neivv** [comment]
Okay, all in all if the 64-bit build works for you then it's probably not worth digging too much into the reason why 32-bit build breaks. Might just be that wine matches windows behaviour better on 64-bit or something? Also, when you said that SC:R works under wine without samase, were you running 32- or 64-bit exe there?

Though from what I did look at the wine logs, it seems that the EXCEPTION_ILLEGAL_INSTRUCTION is not the cause, just close to the actual cause of crash. The game is intentionally executing illegal instruction, verifying that the exception handler is being ran as expected with expected values and continuing forward.
There are other illegal instruction exceptions in the log also from the game executable that have similar checks, so it seems that that the exception checks are being handled properly, it's likely some other checks that get executed right after that exception where it actually breaks. There are 8 different callers of the `ip=00580180` function, so it does not seem worth the effort to examine all of those to find the real cause.
And looking at the samase logs, the one thing I thought that may be different in wine was fine too, so out of easy-to-test ideas for now.

I'll probably just move to only supporting 64-bit exe soon, afaik it does not have any drawbacks or bugs or missing features over 32-bit samase.

**Comment by myocytebd** [comment]
> Okay, all in all if the 64-bit build works for you then it's probably not worth digging too much into the reason why 32-bit build breaks. Might just be that wine matches windows behaviour better on 64-bit or something? 

I am curious because the 64-bit build is apparently different from 32-bit build, e.g. 64-bit has a debug window while 32-bit doesn't.  
It is surely doesn't worth deep investigation.  

> Also, when you said that SC:R works under wine without samase, were you running 32- or 64-bit exe there?

I forgot to mention that it was 64-bit exe and 32-bit exe was not tested. I had thought that samase spawns 64-bit process.

> Though from what I did look at the wine logs, it seems that the EXCEPTION_ILLEGAL_INSTRUCTION is not the cause, just close to the actual cause of crash. The game is intentionally executing illegal instruction, verifying that the exception handler is being ran as expected with expected values and continuing forward. There are other illegal instruction exceptions in the log also from the game executable that have similar checks, so it seems that that the exception checks are being handled properly, it's likely some other checks that get executed right after that exception where it actually breaks. There are 8 different callers of the `ip=00580180` function, so it does not seem worth the effort to examine all of those to find the real cause. And looking at the samase logs, the one thing I thought that may be different in wine was fine too, so out of easy-to-test ideas for now.

Thanks for the explanation.

**Comment by neivv** [comment]
> I am curious because the 64-bit build is apparently different from 32-bit build, e.g. 64-bit has a debug window while 32-bit doesn't.

Ah right, the debug window is a newer thing I don't want to test and maintain on both versions so it isn't enabled on 32-bit build. There are few other smaller patches that are similarly not trivial to port to 32-bit exe and only enabled on 64-bit one, but there's no way they are related to 64-bit samase being stable on wine.

> I forgot to mention that it was 64-bit exe and 32-bit exe was not tested. I had thought that samase spawns 64-bit process.

Right, samase supported 32-bit exe only since 7 years ago there wasn't a 64-bit SC:R =) And then it took a lot of effort to port all patches it supported over to 64-bit one, only really finished this year..

Oh and since a few people have been able to play mods over battle.net using the 32-bit exe without getting banned, the possibility of 64-bit exe getting different treatment (No data that would confirm/deny anything though), has also been a reason why 64-bit support hadn't been too big of a priority.
