### ISSUE TITLE
this is a question about using samase

### ISSUE THREAD

**Issue by krashaon** [neivv/mtl#2]
http://www.staredit.net/topic/17430/8/

At the outset, I'm using samase very useful. Thank you!
I'm asking you a question after seeing the samase post on staredit. 
I was going to ask staredit, but I can't sign up for a new member
so I'm sorry to ask you here.

Is it possible to run in UDP instead of single play when using '--map' among the commands of Samase?
or after turning on Starcraft using samase, can I replace the file(anim/script...) once again?

**Comment by neivv** [comment]
Launching to an UDP game is more difficult to do than a single player game, so it unfortunately is not supported.

> after turning on Starcraft using samase, can I replace the file(anim/script...) once again?

You mean having game use new files without having to close and restart?
That depends on the file, .dat files get reloaded every time a map starts (images.dat maybe not), but reloading anims requires restarting the entire process. Try and see which files work.
Also if you specifically care about aiscript reloading, a more recent build than what I have bothered to update on staredit got that added in (e.g. from here https://drive.google.com/drive/folders/1fkZdVXFWVoI8jj-ubkrAt3yGVeJkjsOR )

**Comment by krashaon** [comment]
Since my purpose is to change the anim file, I will restart StarCraft and use it.
Thank you for the reply!
